version: '3.8'

services:
  rentalservice:
    build: .
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongoquarkus:27017/reservations
    ports:
      - "9000:9000"
    depends_on:
      - mongoquarkus

  mongoquarkus:
    image: mongo:4.4.6
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
