version: '3.8'

services:
  rentalservice:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mongoquarkus

  mongoquarkus:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
