name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongoquarkus:
        image: mongo:4.4.6
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean package -Dquarkus.mongodb.connection-string=mongodb://mongoquarkus:27017/?authSource=admin

      - name: Run tests
        run: mvn -B test -Dquarkus.mongodb.connection-string=mongodb://mongoquarkus:27017/?authSource=admin